language: java
sudo: false
addons:
  apt_packages:
    - pandoc
install: ''
script:
- export TERM=dumb
- './gradlew generateDocx'
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: N4258zuzvzKlhJGnuX3Qy4hK9/L8l3Tph00Z3sMnhmqRzG/f4BYMJEsZ9tSrDntP6qrqy4YUoHf6/AGrg5ZzCVV6vkEupd6jcV3r9e4VFl3Uwatw7+K3iM75nOMVBH6j0ZB5ThR4MmPO1zMG2GXD/tglT2x37rtDMy/v2CJG5No=
  file:
    - $TRAVIS_BUILD_DIR/build/index.pdf
    - $TRAVIS_BUILD_DIR/build/index.docx
  skip_cleanup: true
  on:
    tags: true
    repo: arc42/quality-requirements
